# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dirsizes.ui'
#
# Created: Sat Jan 31 09:31:58 2015
#      by: PyQt5 UI code generator 5.4
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(313, 350)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/AppIcon/icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.softdistlabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setItalic(True)
        self.softdistlabel.setFont(font)
        self.softdistlabel.setText("")
        self.softdistlabel.setAlignment(QtCore.Qt.AlignCenter)
        self.softdistlabel.setObjectName("softdistlabel")
        self.verticalLayout.addWidget(self.softdistlabel)
        self.softdistsize = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.softdistsize.setFont(font)
        self.softdistsize.setText("")
        self.softdistsize.setAlignment(QtCore.Qt.AlignCenter)
        self.softdistsize.setObjectName("softdistsize")
        self.verticalLayout.addWidget(self.softdistsize)
        self.softdistbutton = QtWidgets.QPushButton(self.centralwidget)
        self.softdistbutton.setText("")
        self.softdistbutton.setObjectName("softdistbutton")
        self.verticalLayout.addWidget(self.softdistbutton)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.softdistdownlabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setItalic(True)
        self.softdistdownlabel.setFont(font)
        self.softdistdownlabel.setText("")
        self.softdistdownlabel.setAlignment(QtCore.Qt.AlignCenter)
        self.softdistdownlabel.setObjectName("softdistdownlabel")
        self.verticalLayout.addWidget(self.softdistdownlabel)
        self.softdistdownsize = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.softdistdownsize.setFont(font)
        self.softdistdownsize.setText("")
        self.softdistdownsize.setAlignment(QtCore.Qt.AlignCenter)
        self.softdistdownsize.setObjectName("softdistdownsize")
        self.verticalLayout.addWidget(self.softdistdownsize)
        self.softdistdownbutton = QtWidgets.QPushButton(self.centralwidget)
        self.softdistdownbutton.setText("")
        self.softdistdownbutton.setObjectName("softdistdownbutton")
        self.verticalLayout.addWidget(self.softdistdownbutton)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.downloadlabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setItalic(True)
        self.downloadlabel.setFont(font)
        self.downloadlabel.setText("")
        self.downloadlabel.setAlignment(QtCore.Qt.AlignCenter)
        self.downloadlabel.setObjectName("downloadlabel")
        self.verticalLayout.addWidget(self.downloadlabel)
        self.downloadsize = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.downloadsize.setFont(font)
        self.downloadsize.setText("")
        self.downloadsize.setAlignment(QtCore.Qt.AlignCenter)
        self.downloadsize.setObjectName("downloadsize")
        self.verticalLayout.addWidget(self.downloadsize)
        self.downloadbutton = QtWidgets.QPushButton(self.centralwidget)
        self.downloadbutton.setText("")
        self.downloadbutton.setObjectName("downloadbutton")
        self.verticalLayout.addWidget(self.downloadbutton)
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout.addWidget(self.line_3)
        self.documentslabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setItalic(True)
        self.documentslabel.setFont(font)
        self.documentslabel.setText("")
        self.documentslabel.setAlignment(QtCore.Qt.AlignCenter)
        self.documentslabel.setObjectName("documentslabel")
        self.verticalLayout.addWidget(self.documentslabel)
        self.documentssize = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.documentssize.setFont(font)
        self.documentssize.setText("")
        self.documentssize.setAlignment(QtCore.Qt.AlignCenter)
        self.documentssize.setObjectName("documentssize")
        self.verticalLayout.addWidget(self.documentssize)
        self.documentsbutton = QtWidgets.QPushButton(self.centralwidget)
        self.documentsbutton.setText("")
        self.documentsbutton.setObjectName("documentsbutton")
        self.verticalLayout.addWidget(self.documentsbutton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem)
        self.warninglabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(False)
        font.setItalic(True)
        font.setUnderline(True)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.warninglabel.setFont(font)
        self.warninglabel.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.warninglabel.setObjectName("warninglabel")
        self.verticalLayout.addWidget(self.warninglabel)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ShanBox"))
        self.warninglabel.setText(_translate("MainWindow", "The app count the files and folders that are hidden by the OS"))

import res_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

